apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "banking-platform.fullname" . }}-config
  labels:
    {{- include "banking-platform.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.external.kafkaBootstrapServers | quote }}
  REDIS_HOST: {{ .Values.external.redisHost | quote }}
  REDIS_PORT: {{ .Values.external.redisPort | quote }}
  KEYCLOAK_ISSUER_URI: {{ .Values.external.keycloakIssuerUri | quote }}
  KEYCLOAK_JWK_SET_URI: {{ .Values.external.keycloakJwkSetUri | quote }}
  MANAGEMENT_OTLP_TRACING_ENDPOINT: {{ .Values.global.otlpTracingEndpoint | quote }}
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: {{ .Values.global.tracingSampleProbability | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.global.otelExporterOtlpEndpoint | quote }}
  JAVA_TOOL_OPTIONS: {{ .Values.global.javaToolOptions | quote }}
