{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banking-platform.postgresSecretName" . }}
  labels:
    {{- include "banking-platform.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgres.usernameKey }}: {{ .Values.postgres.username | b64enc | quote }}
  {{ .Values.postgres.passwordKey }}: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
