global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]
  - job_name: customer-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["customer-service:8080"]
  - job_name: account-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["account-service:8080"]
  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8080"]
  - job_name: audit-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["audit-service:8080"]
  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8080"]
